(deftheme molokai-tuned
  "Molokai tuned")

(custom-theme-set-faces
 'molokai-tuned
 '(cursor ((t (:background "#F8F8F0"))))
 '(bold ((t (:weight bold))))
 '(bold-italic ((t (:weight bold :slant italic))))
 '(custom-face-tag ((t (:foreground "#66D9EF" :weight bold))))
 '(custom-state ((t (:foreground "#A6E22E"))))
 '(italic ((t (:slant italic))))
 '(region ((t (:background "#111115"))))
 '(underline ((t (:underline t))))
 '(css-selector ((t (:foreground "#F92672"))))
 '(css-property ((t (:foreground "#66D9EF"))))
 '(diff-added ((t (:foreground "#A6E22E" :weight bold))))
 '(diff-context ((t (:foreground "#F8F8F2"))))
 '(diff-file-header ((t (:foreground "#66D9EF" :background nil))))
 '(diff-indicator-added ((t (:foreground "#A6E22E"))))
 '(diff-indicator-removed ((t (:foreground "#F92672"))))
 '(diff-header ((t (:foreground "#F8F8F2" :background "#232526"))))
 '(diff-hunk-header ((t (:foreground "#AE81FF" :background "#232526"))))
 '(diff-removed ((t (:foreground "#F92672" :weight bold))))
 '(escape-glyph ((t (:foreground "#E6DB74"))))
 '(minibuffer-prompt ((t (:foreground "#66D9EF"))))
 '(mode-line ((t (:background "#000000" :foreground "#F8F8F2"))))
 '(mode-line-buffer-id ((t (:foreground nil :background "#000000" :weight semi-bold))))
 '(mode-line-inactive ((t (:foreground "#BCBCBC" :background "#000000" (quote :box) (:line-width 1 :color "#232526")))))
 '(font-lock-builtin-face ((t (:foreground "#A6E22E"))))
 '(font-lock-comment-face ((t (:foreground "#607087" :slant italic))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#465457" :slant italic))))
 '(font-lock-constant-face ((t (:foreground "#AE81FF"))))
 '(font-lock-doc-face ((t (:foreground "#E6DB74" :slant italic))))
 '(font-lock-function-name-face ((t (:foreground "#F92672" :slant italic))))
 '(font-lock-keyword-face ((t (:foreground "#66D9EF"))))
 '(font-lock-negation-char-face ((t (:weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#A6E22E"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold))))
 '(font-lock-string-face ((t (:foreground "#E6DB74"))))
 '(font-lock-type-face ((t (:foreground "#66D9EF"))))
 '(font-lock-variable-name-face ((t (:foreground "#F92672"))))
 '(font-lock-warning-face ((t (:foreground "#FFFFFF" (quote :background) "#333333"))))
 '(fringe ((t (:background "#1B1D1E"))))
 '(highlight ((t (:foreground "white" :weight bold))))
 '(hl-line ((t (:background "#293739"))))
 '(ido-first-match ((t (:foreground "#A6E22E" :weight bold))))
 '(ido-only-match ((t (:foreground "#A6E22E"))))
 '(ido-subdir ((t (:foreground "#FD971F"))))
 '(isearch ((t (:foreground "#C4BE89" :background "#000000"))))
 '(isearch-fail ((t (:foreground "#FFFFFF" :background "#333333"))))
 '(lazy-highlight ((t (:foreground "#465457" :background "#000000"))))
 '(markdown-italic-face ((t (:slant italic))))
 '(markdown-bold-face ((t (:weight bold))))
 '(markdown-header-face ((t (:weight normal))))
 '(markdown-header-face-1 ((t (:foreground "#66D9EF"))))
 '(markdown-header-face-2 ((t (:foreground "#F92672"))))
 '(markdown-header-face-3 ((t (:foreground "#A6E22E"))))
 '(markdown-header-face-4 ((t (:foreground "#AE81FF"))))
 '(markdown-header-face-5 ((t (:foreground "#E6DB74"))))
 '(markdown-header-face-6 ((t (:foreground "#66D9EF"))))
 '(markdown-inline-code-face ((t (:foreground "#66D9EF"))))
 '(markdown-list-face ((t (:foreground "#A6E22E"))))
 '(markdown-blockquote-face ((t (:slant italic))))
 '(markdown-pre-face ((t (:foreground "#AE81FF"))))
 '(markdown-link-face ((t (:foreground "#66D9EF"))))
 '(markdown-reference-face ((t (:foreground "#66D9EF"))))
 '(markdown-url-face ((t (:foreground "#E6DB74"))))
 '(markdown-link-title-face ((t (:foreground "#F92672"))))
 '(markdown-comment-face ((t (:foreground "#465457"))))
 '(markdown-math-face ((t (:foreground "#AE81FF" :slant italic))))
 '(outline-1 ((t (:foreground "#C4BE89"))))
 '(outline-2 ((t (:foreground "#FD971F"))))
 '(outline-3 ((t (:foreground "#EF5939"))))
 '(outline-4 ((t (:foreground "#F92672"))))
 '(outline-5 ((t (:foreground "#960050"))))
 '(outline-6 ((t (:foreground "#AE81FF"))))
 '(outline-7 ((t (:foreground "#66D9EF"))))
 '(outline-8 ((t (:foreground "#A6E22E"))))
 '(rainbow-delimiters-depth-1-face ((t (:inherit outline-1))))
 '(rainbow-delimiters-depth-2-face ((t (:inherit outline-2))))
 '(rainbow-delimiters-depth-3-face ((t (:inherit outline-3))))
 '(rainbow-delimiters-depth-4-face ((t (:inherit outline-4))))
 '(rainbow-delimiters-depth-5-face ((t (:inherit outline-5))))
 '(rainbow-delimiters-depth-6-face ((t (:inherit outline-6))))
 '(rainbow-delimiters-depth-7-face ((t (:inherit outline-7))))
 '(rainbow-delimiters-depth-8-face ((t (:inherit outline-8))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "#BCA3A3"))))
 '(secondary-selection ((t (:background "#272822"))))
 '(shadow ((t (:foreground "#566467"))))
 '(undo-tree-visualizer-active-branch-face ((t (:inherit default))))
 '(undo-tree-visualizer-current-face ((t (:foreground "#EF5939"))))
 '(undo-tree-visualizer-default-face ((t (:inherit shadow))))
 '(undo-tree-visualizer-register-face ((t (:foreground "E6DB74"))))
 '(undo-tree-visualizer-unmodified-face ((t (:foreground "#66D9EF"))))
 '(widget-inactive ((t (:background "#ff0000"))))
 '(sp-pair-overlay-face ((t nil)))
 '(helm-selection ((t (:distant-foreground "black" :background "dark slate gray"))))
 '(helm-source-header ((t (:foreground "white" :weight bold :height 1.1))))
 '(mode-line-highlight ((t (:foreground "cadet blue"))))
 '(company-scrollbar-bg ((t (:background "dark slate gray"))))
 '(company-tooltip ((t (:background "dark slate gray" :foreground "white"))))
 '(company-scrollbar-fg ((t (:background "#1c2c2c"))))
 '(company-tooltip-annotation ((t (:foreground "light salmon"))))
 '(company-tooltip-selection ((t (:background "#4f8e90"))))
 '(show-paren-match ((t (:background "dark cyan" :foreground "white"))))
 '(show-paren-mismatch ((t (:background "purple" :foreground "white"))))
 '(vertical-border ((t (:background "#1B1D1E" :foreground "#1B1D1E"))))
 '(tooltip ((t (:background "#2d4d4d" :foreground "#F8F8F2"))))
 '(custom-button ((t (:background "#101A1B" :foreground "#F8F8F2" :box (:line-width 1 :color "dim gray")))))
 '(custom-button-mouse ((t (:box (:line-width 1 :color "dim gray") :foreground "#F8F8F2" :background "#2d4d4d"))))
 '(custom-button-pressed ((t (:background "#2d4d4d" :foreground "#F8F8F2" :box (:line-width 2 :color "dim gray" :style pressed-button)))))
 '(widget-single-line-field ((t (:background "#1f2d2c"))))
 '(widget-field ((t (:background "#1f2d2c"))))
 '(helm-ff-directory ((t (:foreground "dark cyan"))))
 '(helm-ff-dotted-symlink-directory ((t (:foreground "magenta"))))
 '(helm-ff-symlink ((t (:foreground "DarkOrange"))))
 '(helm-ff-prefix ((t (:foreground "black" :background "yellow"))))
 '(company-preview-common ((t (:background "#101A1B" :foreground "white"))))
 '(org-level-1 ((t (:height 1.0 :weight normal :slant normal :foreground "turquoise3" :inherit (variable-pitch)))))
 '(org-level-2 ((t (:height 1.0 :weight normal :slant normal :foreground "mediumseagreen" :inherit (variable-pitch)))))
 '(org-level-3 ((t (:height 1.0 :weight normal :slant normal :foreground "turquoise3" :inherit (variable-pitch)))))
 '(org-level-4 ((t (:height 1.0 :weight normal :slant normal :foreground "mediumseagreen" :inherit (variable-pitch)))))
 '(org-done ((t (:foreground "lime green" :weight bold))))
 '(org-todo ((t (:foreground "deep pink" :weight bold))))
 '(org-special-keyword ((t (:foreground "dark cyan" :height 0.9))))
 '(org-date ((t (:foreground "gold2" :underline nil :height 0.9))))
 '(org-link ((t (:foreground "deepskyblue2" :height 0.9))))
 '(org-document-title ((t (:inherit (variable-pitch) :height 1.2))))
 '(helm-match ((t (:foreground "light sea green" :weight bold))))
 '(default ((t (:background "#1B1D1E" :foreground "#F8F8F2"))))
 '(org-priority ((t (:foreground "gold")))))

(provide-theme 'molokai-tuned)
